# Generated by Django 5.2.7 on 2025-12-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_add_created_by_workspace_update_assignee"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tasks that must be completed before this task",
                related_name="dependent_tasks",
                to="tasks.task",
            ),
        ),
    ]
